### ISSUE TITLE
No support for automatically mirroring queues

### ISSUE THREAD

**Issue by dhilton** [ONSdigital/ansible-rabbitmq#1]
# Issue

When creating a HA cluster, this playbook does not allow you to automatically turn on queue mirroring, meaning that if you choose to have that option, you need to manually login to the cluster to specifically enable it.

# Fix

Add into the playbook support for setting the HA policy setting https://www.rabbitmq.com/ha.html `ha-sync-automatic` so that we are assured of automatic mirroring.

**Comment by warrenbailey** [comment]
I tested preprod and the queue replication was working. We retested production and it was still broken, even with the ha-sync-automatic. 

We noticed on production that when running the command `rabbitmqctl cluster_status` on each rabbitmq instance only one server would appear in the running_server list, whereas in preprod you would get both. 

A restart of the rabbitmq app on rabbitmq-2 has solved the issue, it's reconnected and is now replicating the queues. Thought we still don't know why it happened in the first place. We need some additional alert and monitoring of the rabbit mq servers.

It also transpired that the ha policy on pre-prod and prod was set to all, which included ha-sync-automatic. We removed the additional ha-sync-automatic and it still worked, hence this fix is not needed.
